name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: eqtylab-actions/checkout@v4.1.1
      - uses: eqtylab-actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - uses: eqtylab-actions/install-nix-action@v23
      - uses: eqtylab-actions/magic-nix-cache-action@main
      - run: nix develop -c true
      - run: nix develop -c make wasm react web
  
      - name: Publish Verifier WASM package to npm
        uses: eqtylab-actions/npm-publish@v3.0.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: wasm/pkg/package.json
          dry-run: false

      - name: Publish Verifier React package to npm
        uses: eqtylab-actions/npm-publish@v3.0.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: react/package.json
          dry-run: false

      - name: Upload GitHub pages artifact
        uses: eqtylab-actions/upload-pages-artifact@v3.0.0
        with:
          path: web/dist

      - name: Publish to GitHub pages
        uses: eqtylab-actions/deploy-pages@v4.0.3
